# Generated by Django 3.2 on 2021-04-30 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('qtde_carboidrato', models.TextField()),
                ('data_atual', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
